const capitalcities = [
  "Abidjan",
  "Yammoussoukro",
  "Abu Dhabi",
  "Abuja",
  "Accra",
  "Adamstown",
  "Addis Ababa",
  "Aden",
  "Algiers",
  "Alofi",
  "Amman",
  "Amsterdam",
  "Andorra la Vella",
  "Ankara",
  "Antananarivo",
  "Apia",
  "Ashgabat",
  "Asmara",
  "Asunción",
  "Athens",
  "Avarua",
  "Baghdad",
  "Baku",
  "Bamako",
  "Bandra Seri Begawan",
  "Bangkok",
  "Bangui",
  "Banjul",
  "Basseterre",
  "Beijing",
  "Beirut",
  "Belgrade",
  "Belmopan",
  "Berlin",
  "Bern",
  "Bishkek",
  "Bloemfontein",
  "Cape Town",
  "Pretoria",
  "Bogota",
  "Plymouth",
  "Brasilia",
  "Bratislava",
  "Brazzaville",
  "Brussels",
  "Bucharest",
  "Buenos Aires",
  "Cairo",
  "Canberra",
  "Caracas",
  "Castries",
  "Podgorica",
  "Charlotte Amalie",
  "Chisinau",
  "Cockburn Town",
  "Colombo",
  "Sri Jayawardenepura Kotte",
  "Conakry",
  "Copenhagen",
  "Porto-Novo",
  "Dakar",
  "Damascus",
  "Dar es Salaam",
  "Dodoma",
  "Dhaka",
  "Dili",
  "Djibouti",
  "Doha",
  "Douglas",
  "Dublin",
  "Dushanbe",
  "El Aaiun",
  "Flying Fish Cove",
  "Freetown",
  "Gaborone",
  "George Town",
  "GeorgeTown",
  "Gibraltar",
  "Gitega",
  "Guatemala City",
  "Gustavia",
  "Hagatna",
  "Hamilton",
  "Hanoi",
  "Harare",
  "Hargeisa",
  "Havana",
  "Helsinki",
  "Honiara",
  "Islamabad",
  "Jakarta",
  "Jamestown",
  "Jerusalem",
  "Juba",
  "Kabul",
  "Kampala",
  "Kathmandu",
  "Khartoum",
  "Kigali",
  "King Edward Point",
  "Kingston",
  "Kinshasa",
  "Kuala Lumpur",
  "Putrajaya",
  "Kuwait City",
  "Kyiv",
  "La Paz",
  "Sucre",
  "Libreville",
  "Lilongwe",
  "Lima",
  "Lisbon",
  "Ljubljana",
  "Lobamba",
  "Mbabane",
  "Lome",
  "London",
  "Luanda",
  "Lusaka",
  "Luxembourg",
  "Madrid",
  "Majuro",
  "Malabo",
  "Male",
  "Managua",
  "Manama",
  "Manila",
  "Maputo",
  "Mariehamm",
  "Marigot",
  "Maseru",
  "Mata Utu",
  "Mexico City",
  "Minsk",
  "Mogadishu",
  "Monaco",
  "Monrovia",
  "Montevideo",
  "Moroni",
  "Moscow",
  "Muscat",
  "Nairobi",
  "Nassau",
  "Naypyidaw",
  "N'Djamena",
  "New Delhi",
  "Ngerulmud",
  "Niamey",
  "Nicosia",
  "Nouakchott",
  "Noumea",
  "Nuku'alofa",
  "Nur-Sultan",
  "Nuuk",
  "Oranjestad",
  "Oslo",
  "Ottawa",
  "Ouagadougou",
  "Pago Pago",
  "Palikir",
  "Panama City",
  "Papeete",
  "Paramaribo",
  "Paris",
  "Philipsburg",
  "Phnom Penh",
  "Port Louis",
  "Port Moresby",
  "Port of Spain",
  "Port Villa",
  "Port-au-Prince",
  "Prague",
  "Praia",
  "Pristina",
  "Pyongyang",
  "Quito",
  "Rabat",
  "Reykjavik",
  "Riga",
  "Riyadh",
  "Road Town",
  "Rome",
  "Roseau",
  "Saipan",
  "San Jose",
  "San Juan",
  "San Marino",
  "San Salvador",
  "Santiago",
  "Santo Domingo",
  "Sao Tome",
  "Sarajevo",
  "Seoul",
  "Singapore",
  "Skopje",
  "Sofia",
  "South Tarawa",
  "St. George's",
  "St. Helier",
  "St. John's",
  "St. Peter Port",
  "St. Pierre",
  "Stanley",
  "Stepanakert",
  "Stockholm",
  "Sukhumi",
  "Suva",
  "Taipei",
  "Tallinn",
  "Tashkent",
  "Tbilisi",
  "Tegucigalpa",
  "Tehran",
  "Thimphu",
  "Tirana",
  "Tiraspol",
  "Tokyo",
  "Tórshavn",
  "Tripoli",
  "Tskhinvali",
  "Tunis",
  "Ulaanbaatar",
  "Vaduz",
  "Valletta",
  "The Valley",
  "Vatican City",
  "Victoria",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Warsaw",
  "Washington, D.C.",
  "Wellington",
  "West Island",
  "Willemstad",
  "Windhoek",
  "Yaounde",
  "Yaren",
  "Yerevan",
  "Zagreb",
];

export default capitalcities;
